### ISSUE TITLE
Error 502.5 when installing Passcore 3.0.1

### ISSUE THREAD

**Issue by vivi-san** [unosquare/passcore#104]
Hello

I have the Passcore v2 installed on my IIS server and I would like to install the new version 3.0.1 but I have a problem to install this version.

When I browse the https url, I received a HTTP Error 502.5 - Process Failure.

I 've enabled the log through web.config file, there is an export of log stdout file : 
Unhandled Exception: System.TypeLoadException: Could not load type 'System.AppContext' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Unosquare.PassCore.Web.Startup.Main(String[] args)

In addition, I've few errors logged on event viewer : 
1- Application 'MACHINE/WEBROOT/APPHOST/RESETPWD' with physical root 'C:\inetpub\ResetPwd\' failed to start process with commandline 'C:\inetpub\ResetPwd\Unosquare.PassCore.Web.exe ', ErrorCode = '0x80004005 : ff.

2- Faulting application name: Unosquare.PassCore.Web.exe, version: 1.0.0.0, time stamp: 0x94075f1d
Faulting module name: KERNELBASE.dll, version: 6.2.9200.22141, time stamp: 0x58f11bee
Exception code: 0xe0434352
Fault offset: 0x00017f2a
Faulting process id: 0x1a44
Faulting application start time: 0x01d39049044622b3
Faulting application path: C:\inetpub\ResetPwd\Unosquare.PassCore.Web.exe
Faulting module path: C:\Windows\SYSTEM32\KERNELBASE.dll
Report Id: 420a8627-fc3c-11e7-93f7-2c59e541ad9b
Faulting package full name: 
Faulting package-relative application ID: 

Could you please help me to resolve this issue ?

Thanks
Rgds
[stdout_5608_2018118104220.log](https://github.com/unosquare/passcore/files/1642593/stdout_5608_2018118104220.log)

**Comment by veinom** [comment]
Perhaps you have to install the latest version of the .Net Core bundle?

https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore2x#install-the-net-core-windows-server-hosting-bundle

**Comment by vivi-san** [comment]
I've installed Microsoft Visual C++ 2015 Redistributable, then I've installed the .NET Core Windows Server Hosting bundle (DotNetCore.2.0.5-WindowsHosting.exe file).
The server has been restarted to apply changes.

Maybe I miss something ?

**Comment by geoperez** [comment]
Did you restart IIS?

**Comment by vivi-san** [comment]
Yes, tried "iisreset" and the VM has been restarted as well, but same results.
The previous version works fine on the same server.

All of the "Application Development Features" were installed under "World Wide Web Services" through Server Manager.

**Comment by geoperez** [comment]
Try running `dotnet --info` and paste your output.

**Comment by fabiocremo** [comment]
I have the issue, the dotnet --info output is:

PS C:\Windows\system32> dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.2.9200
 OS Platform: Windows
 RID:         win8-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

**Comment by geoperez** [comment]
You are using the right version. Did you restart your server?

**Comment by fabiocremo** [comment]
yes i tried, if it usefull, below the logs

Application startup exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Microsoft.Extensions.Configuration.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Unosquare.PassCore.Web.Startup..ctor(IHostingEnvironment environment)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by Silesiant** [comment]
I am running into the same issue as well.  I am running this on a 2k8R2 server, if that helps.  I have tried both 3.0.0 and 3.0.1, with the same results.

**Comment by vivi-san** [comment]
There it is my output of cmd "dotnet --info" :

PS C:\Windows\system32> dotnet --info

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

My server is a Win2012 Std.

**Comment by geoperez** [comment]
@jpalcala can you take a look at this?

**Comment by jpalcala** [comment]
Did you all perform a clean install or did you overwrite all files from a previous version?

**Comment by vivi-san** [comment]
Personally,  I've created a new subfolder into c:\inetpub to copy all the new files from v3.0.1.
Then on IIS server, I've created a new application pool and a new site.

**Comment by Silesiant** [comment]
I did both.  I did a clean install of 3.0.1, overwrote with 3.0.0 after receiving the error, and then did a clean 3.0.0 install after receiving it again.  now I'm back to a 3.0.1 clean install.

**Comment by jpalcala** [comment]
Could you all please try and execute the `Unosquare.PassCore.Web.exe` file using cmd as Administrator? you should see an output like this:

>C:\inetput\Passcore> Unosquare.PassCore.Web.exe
Hosting environment: Production
Content root path: C:\inetpub\Passcore
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.

**Comment by Silesiant** [comment]
When I run it manually, I get the following:
```
Unhandled Exception: System.TypeLoadException: Could not load type 'System.AppContext' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Unosquare.PassCore.Web.Startup.Main(String[] args)
```

**Comment by geoperez** [comment]
Did you unblock all the files? Do you see the `System.AppContext.dll` file in your folder?

**Comment by Silesiant** [comment]
I can't see any blocked files.  System.AppContext.dll is in the folder.

**Comment by vivi-san** [comment]
Same error in my environnment : 

Unhandled Exception: System.TypeLoadException: Could not load type 'System.AppContext' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Unosquare.PassCore.Web.Startup.Main(String[] args)

System.AppContext.dll is in the folder and the file isn't blocked.

**Comment by geoperez** [comment]
Do you have the [.NET Framework 4.6.1](https://www.microsoft.com/en-us/download/details.aspx?id=49982) installed? This is still a dependency for Active Directory access.

**Comment by Silesiant** [comment]
4.6.1 is not installed.  4.7 was just installed yesterday from our standard Windows updates for the month.  I no longer get the 502.5 errors, but just a screen saying "Loading PassCore".  

I will install 4.6.1, and see if that does it.

**Comment by Silesiant** [comment]
I installed 4.6.1, but I still only get the "Loading PassCore" page.  manually running Unosquare.PassCore.Web.exe is successful.

**Comment by geoperez** [comment]
That's a different issue, did you mount the parent folder or `wwwfolder `at IIS?

**Comment by vivi-san** [comment]
After installing .NET 4.6.1, the problem is solved.
Thanks for your support ^^
