### ISSUE TITLE
Have followed trouble shooting but getting error

### ISSUE THREAD

**Issue by mwgevans** [unosquare/passcore#11]
Just getting a blank page waiting for ever in browser. Have run the DNX command manually to see what's going wrong and getting the below details - which don't mean much to me.

D:\Program Files\PassCore\approot>"D:\Program Files\PassCore\approot\runtimes\dn
x-clr-win-x86.1.0.0-rc2-16357\bin\dnx.exe" --project "D:\Program Files\PassCore\
approot\src\Unosquare.PassCore.Web" --configuration Debug web  > test.log
Error: Unable to load application or execute command 'Microsoft.AspNet.Server.Ke
strel'. Available commands: web.
System.NotSupportedException: An attempt was made to load an assembly from a net
work location which would have caused the assembly to be sandboxed in previous v
ersions of the .NET Framework. This release of the .NET Framework does not enabl
e CAS policy by default, so this load may be dangerous. If this load is not inte
nded to sandbox the assembly, please enable the loadFromRemoteSources switch. Se
e http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence
)
   at System.Reflection.Assembly.LoadFile(String path)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadFile(String assemblyPath)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assem
blyName, IAssemblyLoadContext loadContext)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assem
blyName)
   at Microsoft.Dnx.Host.LoaderContainer.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyNa
me)
   at Microsoft.Dnx.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName nam
e, Func`2 factory)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName ass
emblyName)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, Re
solveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String a
ssemblyFullName)

**Comment by mariodivece** [comment]
This is the exact same message on issue #1 that @Abyssar reported Feb 3. Please try his suggestion.

**Comment by mariodivece** [comment]
No comments in a while. Closing issue.
