### ISSUE TITLE
Error Unable to Load Application

### ISSUE THREAD

**Issue by schmitgreg** [unosquare/passcore#2]
Hi, I apologize if this is a simple fix but I have searched for awhile and I cannot seem to find a solution. The first issue I had is the one that your link predicted (error 500.19, where you correct it by unlocking the section in the configuration editor), however now I have the second issue where the page loads indefinitely. I think their fix would solve it but I think I am implementing it incorrectly. I am wondering if you might assist.

Error: Unable to load application or execute command 'Microsoft.AspNet.Server.Kestrel'. Available commands: web.
System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadFile(String assemblyPath)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.LoaderContainer.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)

I tried installing dnx by getting dnvm and then doing dnvm upgrade -r clr. I tried setting system-wide environment variables to no avail. Can you assist possibly? Should I be using a version of DNX or should I only be using the items that I unzipped? Oh, I'm running windows server 2012.

**Comment by jsoltysiak** [comment]
Hi, have you tried running following command?

`dnu restore`

you should run it inside `passcore/src/Unosquare.PassCore.Web/` folder. This command downloads all missing dependencies for your application. Also make sure you have installed `dnx` `clr` runtime version `1.0.0-rc1-final` or above. You can check available runtimes with:

`dnvm list`

I think those instructions should be included in readme for the application.

**Comment by mariodivece** [comment]
As @jsoltysiak said ensure you have installed dnx correctly and setup. Try his suggestions first. If it doesn't work try upgrading to the latest (unstable) version:
`dnvm upgrade -u`
I did not have to do this on my server but it may help. Let us know how it goes please.

**Comment by schmitgreg** [comment]
jsoltysiak, thank you that worked perfectly. mariodivece, after I tested the first method I upgraded to the latest unstable and everything appears to work perfectly. I will post if any weird issues occur.

Thanks for your help guys!
