### ISSUE TITLE
HTTP Error 500.30 - ANCM In-Process Start Failure with 4.2.0

### ISSUE THREAD

**Issue by MouettE-SC** [unosquare/passcore#381]
**PassCore Server**
- OS: Windows Server 2016
- Provider: Active Directory
- Settings file (without sensitive information): default

**Describe the bug**
We have a working 4.1.1 environment. When switching to version 4.2.0 by changing the physical path of the passcore site in IIS, we hit a HTTP Error 500.30 - ANCM In-Process Start Failure with the following system event :

```
Application: w3wp.exe
CoreCLR Version: 4.700.19.46205
.NET Core Version: 3.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'Zyborg.PassCore.PasswordProvider.LDAP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Zyborg.PassCore.PasswordProvider.LDAP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Unosquare.PassCore.Web.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Unosquare.PassCore.Web.Startup.Main(String[] args) in C:\Unosquare\passcore\src\Unosquare.PassCore.Web\Startup.cs:line 49
```

We've tried restarting everything as well as adding the optional dev features in IIS as suggested in the troubleshooting guide with no success.

**Comment by geoperez** [comment]
Try to download again the package. Thanks for the heads up!
