### ISSUE TITLE
E2E Testing using Selenium

### ISSUE THREAD

**Issue by geoperez** [unosquare/passcore#478]
Complete the following e2e tests:

- [ ] Happy path, using a valid username.
- [ ] Generic error message, using error...

Please check all the cases in the file `src\Unosquare.PassCore.Web\Helpers\DebugPasswordChangeProvider.cs`

**Comment by geoperez** [comment]
I need to check what is going on because the same issue is still happening:

```
 ● Default Suite › ChangePassword_Success

    ElementClickInterceptedError: Element <button class="MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary Mui-disabled Mui-disabled" type="submit"> is not clickable at point (943,515) because another element <form> obscures it

      40 |   });
      41 |   await driver.wait(until.elementLocated(By.xpath(`//div[@id=\'rootNode\']//form/button[@type=\'submit\']`)), configuration.timeout);
    > 42 |   await driver.findElement(By.xpath(`//div[@id=\'rootNode\']//form/button[@type=\'submit\']`)).then(element => {
         |   ^
      43 |     return element.click();
      44 |   });
      45 |   await driver.wait(until.elementLocated(By.css(`.MuiDialogTitle-root`)), configuration.timeout);

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:560:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:486:26)
      at Driver.execute (../node_modules/selenium-webdriver/lib/webdriver.js:699:17)
      at Object.<anonymous>.tests.ChangePassword_Success (commons.js:42:3)
      at Object.<anonymous> (DefaultSuite.test.js:11:5)
```
