### ISSUE TITLE
Could not resolve module @angular/core

### ISSUE THREAD

**Issue by HiawathaRayen** [unosquare/passcore#88]
I'm getting the following error when i try to build the project in VS 2017 

ERROR in Error: Could not resolve module @angular/core
    at StaticSymbolResolver.getSymbolByModule (C:\Users\Me\Downloads\passcore-NetCoreSupport\src\Unosquare.PassCore.Web\node_modules\@angular\compiler\bundles\compiler.umd.js:25631:30)
    at StaticReflector.findDeclaration (C:\Users\Me\Downloads\passcore-NetCoreSupport\src\Unosquare.PassCore.Web\node_modules\@angular\compiler\bundles\compiler.umd.js:24377:63)
    at StaticReflector.initializeConversionMap (C:\Users\Me\Downloads\passcore-NetCoreSupport\src\Unosquare.PassCore.Web\node_modules\@angular\compiler\bundles\compiler.umd.js:24595:36)
    at new StaticReflector (C:\Users\Me\Downloads\passcore-NetCoreSupport\src\Unosquare.PassCore.Web\node_modules\@angular\compiler\bundles\compiler.umd.js:24337:14)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Users\Me\Downloads\passcore-NetCoreSupport\src\Unosquare.PassCore.Web\node_modules\@angular\compiler-cli\src\ngtools_api.js:90:31)
    at AotPlugin._getLazyRoutesFromNgtools (C:\Users\Me\Downloads\passcore-NetCoreSupport\src\Unosquare.PassCore.Web\node_modules\@ngtools\webpack\src\plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\Users\Me\Downloads\passcore-NetCoreSupport\src\Unosquare.PassCore.Web\node_modules\@ngtools\webpack\src\plugin.js:495:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by HiawathaRayen** [comment]
Hash: f342d2fbc668e6d02f15
Version: webpack 3.8.1
Time: 20566ms
 5 assets
[./ClientApp/$$_gendir lazy recursive] ./ClientApp/$$_gendir lazy 160 bytes {main} [built]
[./ClientApp/app/app.material-module.ts] ./ClientApp/app/app.material-module.ts 1.92 kB {vendor} [built]
[./ClientApp/app/app.module.ts] ./ClientApp/app/app.module.ts 2.08 kB {vendor} [built]
[./ClientApp/app/change-password/app.change-password.css] ./ClientApp/app/change-password/app.change-password.css 1.25 kB {vendor} [built]
   [0] multi ./ClientApp/main.ts 28 bytes {main} [built]
   [1] multi ./ClientApp/polyfills.ts 28 bytes {polyfills} [built]
[./ClientApp/app/footer/app.footer.ts] ./ClientApp/app/footer/app.footer.ts 1.05 kB {vendor} [built]
   [2] multi ./ClientApp/assets/styles/indigo-pink.css 28 bytes {styles} [built]
[./ClientApp/app/change-password/app.change-password.ts] ./ClientApp/app/change-password/app.change-password.ts 6.22 kB {vendor} [built]
[./ClientApp/app/dialog/app.dialog.ts] ./ClientApp/app/dialog/app.dialog.ts 1.44 kB {vendor} [built]
[./ClientApp/app/footer/footer.html] ./ClientApp/app/footer/footer.html 1.47 kB {vendor} [built]
[./ClientApp/assets/styles/indigo-pink.css] ./ClientApp/assets/styles/indigo-pink.css 45.1 kB {styles} [built]
[./ClientApp/main.ts] ./ClientApp/main.ts 332 bytes {vendor} [built]
[./ClientApp/polyfills.ts] ./ClientApp/polyfills.ts 351 bytes {polyfills} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 488 bytes {polyfills} {vendor} [built]
    + 365 hidden modules

ERROR in Error: Could not resolve module @angular/core
    at StaticSymbolResolver.getSymbolByModule (C:\Users\Me\Downloads\passcore-NetCoreSupport\src\Unosquare.PassCore.Web\node_modules\@angular\compiler\bundles\compiler.umd.js:25631:30)
    at StaticReflector.findDeclaration (C:\Users\Me\Downloads\passcore-NetCoreSupport\src\Unosquare.PassCore.Web\node_modules\@angular\compiler\bundles\compiler.umd.js:24377:63)
    at StaticReflector.initializeConversionMap (C:\Users\Me\Downloads\passcore-NetCoreSupport\src\Unosquare.PassCore.Web\node_modules\@angular\compiler\bundles\compiler.umd.js:24595:36)
    at new StaticReflector (C:\Users\Me\Downloads\passcore-NetCoreSupport\src\Unosquare.PassCore.Web\node_modules\@angular\compiler\bundles\compiler.umd.js:24337:14)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Users\Me\Downloads\passcore-NetCoreSupport\src\Unosquare.PassCore.Web\node_modules\@angular\compiler-cli\src\ngtools_api.js:90:31)
    at AotPlugin._getLazyRoutesFromNgtools (C:\Users\Me\Downloads\passcore-NetCoreSupport\src\Unosquare.PassCore.Web\node_modules\@ngtools\webpack\src\plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\Users\Me\Downloads\passcore-NetCoreSupport\src\Unosquare.PassCore.Web\node_modules\@ngtools\webpack\src\plugin.js:495:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Child html-webpack-plugin for "index.html":
     1 asset
    [./node_modules/html-webpack-plugin/lib/loader.js!./ClientApp/index.html] ./node_modules/html-webpack-plugin/lib/loader.js!./ClientApp/index.html 2.8 kB {0} [built]

**Comment by HiawathaRayen** [comment]
now it builds but i get the following error in the browser 

vendor.bundle.js:1 Uncaught Error: Can't resolve all parameters for e: ([object Object], [object Object], [object Object], ?).
    at m (vendor.bundle.js:1)
    at t._getDependenciesMetadata (vendor.bundle.js:1)
    at t._getTypeMetadata (vendor.bundle.js:1)
    at t.getNonNormalizedDirectiveMetadata (vendor.bundle.js:1)
    at t.loadDirectiveMetadata (vendor.bundle.js:1)
    at vendor.bundle.js:1
    at Array.forEach (<anonymous>)
    at vendor.bundle.js:1
    at Array.forEach (<anonymous>)
    at t._loadModules (vendor.bundle.js:1)
m @ vendor.bundle.js:1
t._getDependenciesMetadata @ vendor.bundle.js:1
t._getTypeMetadata @ vendor.bundle.js:1
t.getNonNormalizedDirectiveMetadata @ vendor.bundle.js:1
t.loadDirectiveMetadata @ vendor.bundle.js:1
(anonymous) @ vendor.bundle.js:1
(anonymous) @ vendor.bundle.js:1
t._loadModules @ vendor.bundle.js:1
t._compileModuleAndComponents @ vendor.bundle.js:1
t.compileModuleAsync @ vendor.bundle.js:1
e._bootstrapModuleWithZone @ vendor.bundle.js:1
e.bootstrapModule @ vendor.bundle.js:1
./ClientApp/main.ts @ vendor.bundle.js:1
n @ inline.bundle.js:1
0 @ main.bundle.js:1
n @ inline.bundle.js:1
window.webpackJsonp @ inline.bundle.js:1
(anonymous) @ main.bundle.js:1

**Comment by Israel-94** [comment]
Ok, there was a problem with the dependencies, It should work now with the new version

**Comment by HiawathaRayen** [comment]
Thank you!

**Comment by geoperez** [comment]
@HiawathaRayen can I close the issue?

**Comment by HiawathaRayen** [comment]
Yes thank you!
